### ISSUE TITLE
Open Science Grid stratum

### ISSUE THREAD

**Issue by rusholme** [airnandez/sw-lsst-eu#1]
Hi,

Using the LSST CVMFS stack from California. I'm obtaining the files from France, is there a problem with the Open Science Grid mirror?

Thanks, Ben

```
cvmfs_talk -i sw.lsst.eu host info
  [0] http://cclssts1.in2p3.fr/cvmfs/sw.lsst.eu (geographically ordered)
  [1] http://cvmfs-stratum-one.cern.ch/cvmfs/sw.lsst.eu (geographically ordered)
  [2] http://cvmfs-s1goc.opensciencegrid.org/cvmfs/sw.lsst.eu (geographically ordered)
Active host 0: http://cclssts1.in2p3.fr/cvmfs/sw.lsst.eu
```

**Comment by airnandez** [comment]
Hello @rusholme,

you may have already sorted out this issue, but anyway. As far as I can tell, the OpenScienceGrid mirror is working as expected:

```
$ curl --head http://cvmfs-s1goc.opensciencegrid.org/cvmfs/sw.lsst.eu/.cvmfspublished
HTTP/1.1 200 OK
Date: Tue, 23 Jul 2019 07:05:48 GMT
<snip>
```

It is rather surprising that the `cvmfs_talk` tool sort the repositories that way given that you are connected to a network in California.

I'm closing this issue, but feel free to re-open it if needed.
