### ISSUE TITLE
Can *-dev releases be removed?

### ISSUE THREAD

**Issue by airnandez** [airnandez/sw-lsst-eu#5]
In 2019 we did some experiments that resulted in the distribution of some `*-dev` releases.

As of today we have:

```
lsst_distrib/v18.1.0-dev
lsst_distrib/w_2019_19-dev
lsst_distrib/w_2019_44-dev

lsst_sims/sims_w_2019_19-dev
lsst_sims/sims_w_2019_44-dev
```

@heather999 Can the releases above be removed or do you still need them online ?

**Comment by heather999** [comment]
I think removing them is fine - just want to confirm with Johann..  I can't @ him here .. I'll send him a Slack.

**Comment by heather999** [comment]
Heard back from Johann, he agrees, removing the dev installs is just fine. Thanks!

**Comment by airnandez** [comment]
Thanks @heather999. Those `*-dev` releases are now removed. I'm closing this issue.
